In [1]:
# 1
%matplotlib inline
# 2
%load_ext autoreload
%autoreload all
# 3
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import sys
sys.path.append('..')

In [3]:
from src.omniglot_dataset import OmniglotDataset
from src.prototypical_batch_sampler import PrototypicalBatchSampler
import numpy as np

In [4]:
dataset = OmniglotDataset(mode='train', root='TMP')

== Dataset: Found 82240 items 
== Dataset: Found 4112 classes


In [5]:
# Each epoch contains 100 episodes; each episode contains 5 classes with per class 20 samples(support+query)
sampler = PrototypicalBatchSampler(labels = dataset.y,
                                   classes_per_it = 5,
                                   num_samples = 20,
                                   iterations = 100)

In [6]:
len(sampler)
for id,episode in enumerate(sampler):
    if id==1:
        episode
        episode.shape
        episode[10]
        

100

tensor([12328, 41664, 23591, 23587, 54295, 41612, 30526, 12344, 12380, 23543,
        54267, 12352, 23571, 12340, 41660, 12324, 23551, 41668, 30554, 23595,
        30510, 30522, 30534, 12320, 41652, 12376, 41604, 30518, 12372, 54275,
        30546, 54271, 54243, 54251, 23563, 23535, 23559, 23547, 12396, 54319,
        54247, 41676, 30550, 30542, 41616, 12332, 23531, 23523, 54279, 41632,
        41620, 12360, 30530, 54315, 41628, 54303, 54311, 12392, 12356, 23539,
        41600, 30506, 23555, 54287, 30482, 54263, 30502, 23579, 54283, 12336,
        23575, 30498, 41644, 12348, 41672, 30538, 41636, 41656, 54307, 41648,
        54255, 30514, 41640, 23567, 23527, 12388, 41608, 12384, 12368, 30490,
        41624, 23583, 54259, 30558, 30486, 12364, 23599, 54291, 54299, 30494])

torch.Size([100])

tensor(54267)

In [7]:
print("Finished Testing!")

Finished Testing!


___

In [8]:
dataset.y

(0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,


In [9]:
classes, counts = np.unique(dataset.y, return_counts=True)
classes
counts
print('-'*20)
len(dataset.y)
len(classes)
print('-'*20)
np.argwhere(counts!=20)
4122*20

array([   0,    1,    2, ..., 4109, 4110, 4111])

array([20, 20, 20, ..., 20, 20, 20])

--------------------


82240

4112

--------------------


array([], shape=(0, 1), dtype=int64)

82440

In [10]:
import torch
idxs=range(len(dataset.y))
idxs
classes
'-'*20
indexes=np.empty((len(classes), max(counts)), dtype=int) * np.nan
indexes = torch.tensor(indexes)
numel_per_class = torch.zeros_like(torch.tensor(classes))
for idx, label in enumerate(dataset.y):
    label_idx = np.argwhere(classes == label).item()
    indexes[label_idx, np.where(np.isnan(indexes[label_idx]))[0][0]] = idx
    numel_per_class[label_idx] += 1
indexes.to(dtype=torch.int)
numel_per_class

range(0, 82240)

array([   0,    1,    2, ..., 4109, 4110, 4111])

'--------------------'

tensor([[    0,     4,     8,  ...,    68,    72,    76],
        [    1,     5,     9,  ...,    69,    73,    77],
        [    2,     6,    10,  ...,    70,    74,    78],
        ...,
        [82161, 82165, 82169,  ..., 82229, 82233, 82237],
        [82162, 82166, 82170,  ..., 82230, 82234, 82238],
        [82163, 82167, 82171,  ..., 82231, 82235, 82239]], dtype=torch.int32)

tensor([20, 20, 20,  ..., 20, 20, 20])

In [11]:
torch.LongTensor(100)

tensor([140035371502560, 140035371502560,               0,               0,
           502511173742,    433791697005,    408021893228,    433791697008,
           408021893234,    463856468067,    493921239137,             115,
                   1872,            1392, 140030507364320, 140030507364896,
        140030507364992, 140030507363936, 140030507365088, 140030507365280,
        140030507365664, 140030507365568, 140030507365376, 140030507365472,
        140030507365760, 140030507365856, 140030507365952, 140030507366048,
        140030507366144, 140030507366240, 140030507366336, 140030507366432,
        140030507366528, 140030507367008, 140030507367104, 140030507367200,
        140030507367296, 140030507367392, 140030507367488, 140030507367584,
        140030507367680, 140030507367776, 140030507367872, 140030507367968,
        140030507368064, 140030507368160, 140030507368256, 140030507368352,
        140030493960960, 140030493961152, 140030493961536, 140030493961440,
        1400

In [14]:
x = numel_per_class
x.size(dim=0)

4112