In [1]:
# 1
%matplotlib inline
# 2
%load_ext autoreload
%autoreload all
# 3
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import sys
sys.path.append('..')

In [3]:
from src.omniglot_dataset import OmniglotDataset
from src.prototypical_batch_sampler import PrototypicalBatchSampler
import numpy as np

In [4]:
dataset = OmniglotDataset(mode='train', root='TMP')

== Dataset: Found 82240 items 
== Dataset: Found 4112 classes


In [5]:
# Each epoch contains 100 episodes; each episode contains 5 classes with per class 20 samples(support+query)
sampler = PrototypicalBatchSampler(labels = dataset.y,
                                   classes_per_it = 5,
                                   num_samples = 20,
                                   iterations = 100)

In [6]:
len(sampler)
for id,episode in enumerate(sampler):
    if id==1:
        episode
        episode.shape
        episode[10]
        

100

tensor([55144, 77784, 55152, 24605, 77804, 77796, 77820, 24625, 71296, 55124,
        77812, 71328, 24585, 55160, 78937, 71344, 24617, 71332, 55132, 77808,
        78949, 71340, 71292, 55128, 55176, 55172, 55192, 71336, 55136, 24581,
        77772, 71308, 55184, 71300, 77780, 71356, 77824, 78893, 55156, 24613,
        78933, 24569, 24621, 78917, 71324, 78945, 77800, 55148, 71280, 78929,
        71288, 78925, 77776, 77768, 77792, 78913, 77832, 55168, 78905, 78889,
        55120, 77828, 55196, 77760, 24633, 55164, 78921, 24589, 78897, 71320,
        71304, 78885, 71312, 24561, 55140, 78957, 24637, 24601, 24565, 24573,
        77816, 78909, 24629, 71348, 71284, 78901, 78941, 77764, 71316, 78953,
        24597, 24577, 55188, 77836, 77788, 24593, 71352, 24609, 55180, 78881])

torch.Size([100])

tensor(77812)

In [7]:
print("Finished Testing!")

Finished Testing!


___

In [8]:
dataset.y

(0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,


In [9]:
classes, counts = np.unique(dataset.y, return_counts=True)
classes
counts
print('-'*20)
len(dataset.y)
len(classes)
print('-'*20)
np.argwhere(counts!=20)
4122*20

array([   0,    1,    2, ..., 4109, 4110, 4111])

array([20, 20, 20, ..., 20, 20, 20])

--------------------


82240

4112

--------------------


array([], shape=(0, 1), dtype=int64)

82440

In [11]:
import torch
idxs=range(len(dataset.y))
idxs
classes
'-'*20
indexes=np.empty((len(classes), max(counts)), dtype=int) * np.nan
indexes = torch.tensor(indexes)
numel_per_class = torch.zeros_like(torch.tensor(classes))
for idx, label in enumerate(dataset.y):
    label_idx = np.argwhere(classes == label).item()
    indexes[label_idx, np.where(np.isnan(indexes[label_idx]))[0][0]] = idx
    numel_per_class[label_idx] += 1
indexes.to(dtype=torch.int)
numel_per_class

range(0, 82240)

array([   0,    1,    2, ..., 4109, 4110, 4111])

'--------------------'

tensor([[    0,     4,     8,  ...,    68,    72,    76],
        [    1,     5,     9,  ...,    69,    73,    77],
        [    2,     6,    10,  ...,    70,    74,    78],
        ...,
        [82161, 82165, 82169,  ..., 82229, 82233, 82237],
        [82162, 82166, 82170,  ..., 82230, 82234, 82238],
        [82163, 82167, 82171,  ..., 82231, 82235, 82239]], dtype=torch.int32)

tensor([20, 20, 20,  ..., 20, 20, 20])

In [12]:
torch.LongTensor(100)

tensor([140014238695040, 140009435476512, 140009435476224, 140009435476128,
        140009435473536, 140009435474112, 140009435473920, 140009435475552,
        140009435475360, 140009435475168, 140009435478336, 140009435474592,
        140009435474688, 140009435473728, 140009435473440, 140009435473344,
        140009422927712, 140009422927904, 140009422927808, 140009422916864,
        140009422915328, 140009422917056, 140009422916960, 140009422916768,
        140009422916288, 140009422916192, 140009422915904, 140009422916576,
        140009422915808, 140009422916096, 140009422916000, 140009422916672,
        140009422916384, 140009422916480, 140009422914752, 140009422917248,
        140009422917152, 140009422917344, 140009422917440, 140009422917536,
        140009422917728, 140009422917824, 140009422918016, 140009422917920,
        140009422918112, 140009422918208, 140009422918304, 140009422918400,
        140009422918496, 140009422918592, 140009422918688, 140009422918784,
        1400