In [1]:
# 1
%matplotlib inline
# 2
%load_ext autoreload
%autoreload all
# 3
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
from omniglot_dataset import OmniglotDataset
from prototypical_batch_sampler import PrototypicalBatchSampler
import numpy as np

In [3]:
dataset = OmniglotDataset(mode='train', root='TMP')

== Dataset: Found 82240 items 
== Dataset: Found 4112 classes


In [4]:
# Each epoch contains 100 episodes; each episode contains 5 classes with per class 20 samples(support+query)
sampler = PrototypicalBatchSampler(labels = dataset.y,
                                   classes_per_it = 5,
                                   num_samples = 20,
                                   iterations = 100)

In [5]:
len(sampler)
for id,episode in enumerate(sampler):
    if id==1:
        episode
        episode.shape
        episode[10]
        

100

tensor([77150, 71596, 18283, 19518, 71576, 18315, 71592, 19442, 77138, 19510,
        77134, 77186, 19450, 18299, 71528, 71556, 18247, 18251, 77178, 18319,
        77126, 38875, 38807, 38847, 38855, 71520, 38819, 18275, 77130, 77158,
        77194, 18255, 77122, 18295, 19462, 77174, 71584, 19498, 18271, 38851,
        71536, 71588, 18287, 19506, 18259, 77182, 38827, 71544, 77154, 71580,
        71548, 18279, 38867, 71572, 71560, 38843, 77142, 18307, 71564, 18303,
        19474, 77190, 71540, 18267, 71568, 38835, 18291, 77162, 38863, 38871,
        19502, 19458, 19470, 38803, 19446, 19494, 77166, 19486, 18263, 18243,
        38811, 38823, 19466, 77170, 19514, 71524, 38815, 38839, 18311, 71552,
        19482, 77198, 38859, 19454, 38831, 71532, 77146, 38879, 19478, 19490])

torch.Size([100])

tensor(77134)

In [6]:
print("Finished Testing!")

Finished Testing!


___

In [5]:
dataset.y

(0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,
 8,
 9,
 10,
 11,


In [19]:
classes, counts = np.unique(dataset.y, return_counts=True)
classes
counts
print('-'*20)
len(dataset.y)
len(classes)
print('-'*20)
np.argwhere(counts!=20)
4122*20

array([   0,    1,    2, ..., 4109, 4110, 4111])

array([20, 20, 20, ..., 20, 20, 20])

--------------------


82240

4112

--------------------


array([], shape=(0, 1), dtype=int64)

82440

In [37]:
idxs=range(len(dataset.y))
idxs
classes
'-'*20
indexes=np.empty((len(classes), max(counts)), dtype=int) * np.nan
indexes = torch.tensor(indexes)
numel_per_class = torch.zeros_like(torch.tensor(classes))
for idx, label in enumerate(dataset.y):
    label_idx = np.argwhere(classes == label).item()
    indexes[label_idx, np.where(np.isnan(indexes[label_idx]))[0][0]] = idx
    numel_per_class[label_idx] += 1
indexes.to(dtype=torch.int)
numel_per_class

range(0, 82240)

array([   0,    1,    2, ..., 4109, 4110, 4111])

'--------------------'

tensor([[    0,     4,     8,  ...,    68,    72,    76],
        [    1,     5,     9,  ...,    69,    73,    77],
        [    2,     6,    10,  ...,    70,    74,    78],
        ...,
        [82161, 82165, 82169,  ..., 82229, 82233, 82237],
        [82162, 82166, 82170,  ..., 82230, 82234, 82238],
        [82163, 82167, 82171,  ..., 82231, 82235, 82239]], dtype=torch.int32)

tensor([20, 20, 20,  ..., 20, 20, 20])

In [12]:
import torch
torch.LongTensor(100)

tensor([              0,               0,               0, 140536381025840,
        140536381025840,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
                      0,               0,               0,               0,
            